### ISSUE TITLE
Question: Is there a workflow to sign the safe tx using a ledger based account?

### ISSUE THREAD

**Issue by jo-tud** [banteg/ape-safe#4]
Considering the security focus of Gnosis Safes it seems counterproductive to require the private key to reside on the machine where the ape-safe tools are used.

**Comment by banteg** [comment]
It would be possible if Ledger support was added to `eth-account`. It actually has a [ledger branch](https://github.com/ethereum/eth-account/tree/feat/ledger) since a few years ago which is working, but it was never merged and released.

Maybe we can backport this to Brownie so it supports Ledger accounts natively.

Alternatively you can generate a tx and just sign a safe tx hash, [more details here](https://github.com/gnosis/gnosis-py/blob/30d1e57dc68ca73749df3d1abe036eb64f3f4a9c/gnosis/safe/safe_tx.py#L264-L282).

**Comment by jo-tud** [comment]
It would be great to have that integrated in Brownie, many other projects would also profit.
Currently I'm planning on just copying the generated safe_tx.data, value, etc... and pasting it into the Gnosis safe browser UI for a new custom Tx. Should work, shouldn't it?

**Comment by jo-tud** [comment]
Work around: Use Metamask in a browser to create the signature with a ledger and then paste it into the safe-ape script. Just copy the `safeTxHash` and use the below script. It will create the necessary signature with the help of Metamask:

```
// Can be executed in the console of the Gnosis safe site
// Metamask must be unlocked and site must have the sender address connected through Metamask

// UPDATE THIS!
safeTxHash = '';
sender = '';

params = [sender, safeTxHash]
ethereum
  .request({
    method: 'eth_sign',
    params,
  })
  .then((result) => {
    console.log("The signature:" + result)
  })
  .catch((error) => {
    console.log(error)
  });
```

**Comment by banteg** [comment]
Now that brownie has added `clef` support, I think hw wallet signing workflow can be explored.

**Comment by BitcoinLixin** [comment]
> Now that brownie has added `clef` support, I think hw wallet signing workflow can be explored.

Quick question - do you have any plan to add QR code based hardware wallet which can also add ABI to the device to decode the tx to get it fully verified? Would love to hear your comments.

Demo #1:
https://twitter.com/KeystoneWallet/status/1409465608643641347
Demo #2:
https://twitter.com/KeystoneWallet/status/1415316932954255362

**Comment by banteg** [comment]
Added hardware wallet support in #17.
